#awk '{printf("enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target %s --baddr=%s\n",$1,$2)}'
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_03.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ZS0w0YXcxMQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_04.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8xa0RodHF3Ug==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_05.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tUW5Oc0tIbg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_06.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9WY2kxZ3lGRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_07.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9IVHd4bmhOVw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_08.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Fdk5rQTZnWg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_09.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93V3hGMzNKNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94QUphcHpVRw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ZWXRTWDRpdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9pS0VzdTVGRQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9SWDNKRWdzSw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ueVZUVlFQOQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_0f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zVEc0dzRYUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_10.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93eUMzcXhwRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_11.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9rTERKNnRWRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_12.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GZFZyUmZkeg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_13.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9pa00zOGJSTQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_14.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OcGRlRVFCZw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_15.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS82SEU2WFFQRQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_16.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ob3B0NTJXQQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_17.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9mUjFFMXdhcA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_18.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS85dHI3amZOeg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_19.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84Qjh4ZUU5Ug==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zMTVxaUZjTQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9mUU5oQnptZw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zcGhOdDVWcA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GYVkzVmo1Sg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS85aEJxMVRWaw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_1f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84aFVFUnkxdw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_20.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9KNkdmaFEzQg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_21.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DbjJwUE13cQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_22.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yalJXNWJWNQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_23.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9FQUdGNUpFdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_24.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9FalNZOGplUQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_25.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9rMWRiWFl3aQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_26.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS81eE4yTGNHWQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_27.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yZ2pGYkZtag==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_28.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zU1FWY3dHUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_29.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9HV213dFUxag==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9rQlZSRTZFaA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GWHVROXQxWg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94SDJVZUNZdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8yaVl4VGFnaw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hOTl6OEsyOA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_2f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zaXRDTmZaZA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_30.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yOE5vSnZpTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_31.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9YR29Vd2J5cg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_32.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8xaXp0YXBqMQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_33.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Vcm5OVVJXZw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_34.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9vUkhtY3QxYQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_35.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GN252R1I3ZA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_36.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DY1M2cWM2cw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_37.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Wd3ZMbWJKVw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_38.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zUlBVZ3Y0TA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_39.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS91cEVkS1JZQQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS85QU56OHVqRw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS82ZmJzcm9uYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84d2lYbnBBVw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hN3pac2c3cA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oRGF6UkJheA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_3f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9rR1V5YTJ4OA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_40.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS80Z3BMNGN0SA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_41.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9NZHR0MXdrUQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_42.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9nRzl6eUxrZg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_43.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OMUNBakVaRQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_44.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9xZkdSWjM1Uw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_45.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GdlJxenpCbg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_46.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9SZDZoMjN1SA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_47.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9lWjZabnJ2cQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_48.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9CendBeHlIZA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_49.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94TW1FQzZXRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS85U3ZkRUNlaQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yNTQ5WkI1Sw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9uNXJyZGlnNw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9jRFlVaFdDag==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XRVNkdm1Ccg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_4f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS83UkduNUw3WQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_50.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9BY1hVS0NUbg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_51.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ac1hHNDRuWQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_52.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93bjNIQkVHWg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_53.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oeG53SjRUZQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_54.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zYTdlQkQ2OA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_55.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ObzFZc3ZmUg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_56.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oY0huTG1EWg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_57.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS95QWpZTmU5Qw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_58.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zQUEzTDRKYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_59.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS92dUNKcjVzVQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8ySEhiVHdrMg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hUERqRXloYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9NekR3d1VDRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DWkxKRXVpaw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9MTjRzejdncw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_5f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zQmplQ3RVeg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_60.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9FandOM2s2bg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_61.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94amQ2b2VmdA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_62.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ORmhBd0xLRw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_63.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9CUGtqelBnNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_64.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84TGtYNG5Ncg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_65.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9rRnB4YVBSRQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_66.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9INm5mRmU5Mw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_67.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9VNUdHZ0hCNg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_68.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS81RnNGenh6WA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_69.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9NNzZxaUFldQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9aazFZWHRvbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tZFVqb3ZMNg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8xRW5UMjdCOQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8ydlFGZWhzYg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zdEpyaGtEYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_6f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9aTTJFOFBRbQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_70.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9RaHFOOWhqSA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_71.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9nMU5mdnBoOQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_72.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9VOVVCd3VyRw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_73.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93MUJCQW8xYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_74.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9YRG1RcHRiUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_75.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9CemFIaDJ5YQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_76.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Xb2hlN0NrWg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_77.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS82RXEyZjlaYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_78.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9NVzc4dEJzeA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_79.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zaWc4azcxVA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oUVoxb2NIcA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9YTHlXY1JmUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8xODZKdnlGMg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XbjFYbkpYUg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9KVjJwdWtHaw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_7f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9UdjltckxQdQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_80.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OaWlYVUM2eQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_81.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9NNnJIYVVnQw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_82.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9jU1RDWk1zSA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_83.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9MWnJINjVUTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_84.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8xNUtodFRWNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_85.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9paDdVZUNUVA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_86.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tMzdXVDc2bg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_87.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9UUndmRWtNNw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_88.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9WSmNtS0dncg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_89.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9qWVZWMTJZcg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9wNnZQVmlITA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS91TFVrdWdLRg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GeGRUWmQ0Uw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9kMXJOQTFpSg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9uc2tHTnhCTQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_8f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9IbzVlZWNxQg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_90.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hR3BMaGhWaQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_91.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84TjV0UVI3bw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_92.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zalVHZWViVg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_93.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9aZHVqbldmQQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_94.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9CZHBLcEFtdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_95.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9iRU1rNk5rcA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_96.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9uR0E0ZGRVVA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_97.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ZS2l5cG9KRQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_98.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OM1BCS1FGcQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_99.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9uRjdYU0xNZQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DOUc3N3ROVw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS80UkdONUNiaQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS92dXFYOFZyOQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84b3lDbnFaOA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS91ZzU4WXhqYQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_9f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9lTWhScUNydQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84OUJjYmVjTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9HUEJvNXg2RQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS92WDZhUzR5cw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hQlI3SmhKMg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GaURWWVNYaw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zZ2c2RnNCQg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS81TUpuVHkxdA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9EazJIZG5SYQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Rc25IaVh0ag==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_a9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9vZWJSaDJNNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_aa.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DUjdtaFBtcw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ab.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9QYTEzeVFDUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ac.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XbUh5QVJ2bg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ad.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9lcm1jTnFZcQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ae.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8ycEFla0VCWQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_af.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9RTkFKSlU4WA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9iZkMyWXpBdQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9UREJUUmo1VQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9MU0tHTmI0UQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS83UGR4TFZiNw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84SHlBakZBRA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9nQ3RHODhibg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS82VlNYYjNYdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9LVGlQVmR3eg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94R1p6NE40cA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_b9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9STDh5eXZSZQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ba.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS91d0NoR05kdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_bb.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9YNnFxUk5xNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_bc.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9BOUZNWWR3WA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_bd.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS82Z3g0NmhnaQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_be.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9pRVh2TGdpNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_bf.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hRXhIWGR2NQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9HU253TG42Vw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9UZFVWQ0Y4dQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93RTVEbVltdQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ySDFrYlZVcg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tQ1RjbVdlRw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9SczF3akc3Yg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS94QXBFcm1lZA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zQmRjcGdLaA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS91MzFrREZ0VQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_c9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9vR0FuYUNkTA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ca.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9mc1Q2VjhKVg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_cb.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9KWXJQV2tDcQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_cc.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oblY1aGpSMg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_cd.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Wa1lQanlTag==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ce.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OSE5EU2VpTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_cf.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9IV0hzQUF0aQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9BbkY1cmloNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9FTlBaWkNWbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9iVGlKbkFndg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9mVmNkVUZzUQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9hNXJZRmdDQg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ISjZHUTJkTA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9qWGR0YU1qbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Da2FrTXd0aQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9zem16MmsxUw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_d9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9VZVFoVlRQOQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_da.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93VXFXRndjSA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_db.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9SVWc2ZjZuMw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_dc.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9jb1p5ZHhXdQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_dd.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ITW1kc0o4TQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_de.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9pclZ2U0U2ZQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_df.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS81Nk42V0x2TQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS92Z1FDWlR4cw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9kdUUxYnd5bQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9KeDJVWU03QQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9CaEdHc1JmTA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XWEJ1VUxIUg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9HbTVlZjVCbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9MQW1KbWRDMw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9OdnNmSDN4Sw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS80Nm1Oa2F0dA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_e9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XZkE3S2FHNQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ea.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yVndUY2NhdQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_eb.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS8zcTFuRnlWeg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ec.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tUjlaaHBVcw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ed.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9XeHBOMWoyTA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ee.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yMUpSZnh2aw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ef.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9qYXZvalJ2Vg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9aNEZ2TjZkdg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9xOW9mMUNYVQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9HNmJvcDNqbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9oaDhhU3ZuUA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9keVFQeTRxTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9teFhQWHk5cg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9MeVpIU2FhTQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ueUhOM0xkcw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9tOXhMWEtoYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_f9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9vdEM5RlFoQw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_fa.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DTWFvMk5HWA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_fb.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ybXhpSlNiNw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_fc.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9RWFhTU2k3bw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_fd.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ielNkWkVOVA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_fe.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9Za3dOelY5Zw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bps_ff.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9VNFg5blpwQQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_0.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9GVzNBcjg2Qw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_1.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS95Y0dQUVI2eQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_2.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9jdXBpRlpEdw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_3.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9SaDk3UkhQZw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_4.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9wVjNGdlViTg==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_5.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9qVW1VVjlGSw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_6.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9yMldxQXdoMQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_7.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS96WE1oUHhmbw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_8.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9DYlVxSER2ZQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_9.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9jRk12UVF4cQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_a.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9RQVpZbVBNNA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_b.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS84SkFCMXpiVQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_c.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93cHRvWVFOdA==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_d.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS9ENUxSMVA0QQ==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_e.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS80OTRxMkJNYw==
enode.sh ~/rhplay/jsutils/update_bpsarchives.js bpsarchives.json --target bpsxa_f.7z --baddr=aHR0cHM6Ly9waXhlbGRyYWluLmNvbS9hcGkvZmlsZXN5c3RlbS93U25QVERabw==
