<!--
  Rating Factors Help Component
  Auto-generated by generate-rating-help.js
  Do not edit manually - regenerate using: node jstools/generate-rating-help.js
-->
<template>
  <div class="rating-factors-help">
    <div class="help-header">
      <h1>{{ template.introduction.title }}</h1><!-- <A HREF="https://www.twitch.tv">test</A> -->
      <p v-if="template.introduction.description">{{ template.introduction.description }}</p>
      <div v-if="template.introduction.customContent && template.introduction.customContent !== '<!-- Add custom introduction content here -->'" v-html="template.introduction.customContent"></div>
    </div>
    
    <div class="rating-factors-list">
      <div 
        v-for="(factor, index) in template.ratingFactors" 
        :key="factor.internalName"
        class="rating-factor-section"
      >
        <h2 class="factor-title">
          <span class="factor-number">{{ index + 1 }}.</span>
          {{ factor.displayName }}
        </h2>
        
        <div class="factor-meta">
          <div class="meta-item">
            <strong>Internal Name:</strong> <code>{{ factor.internalName }}</code>
          </div>
          <div class="meta-item">
            <strong>Range:</strong> {{ factor.range.min }} to {{ factor.range.max }} stars
          </div>
        </div>
        
        <div v-if="factor.description" class="factor-description">
          <strong>Description:</strong>
          <p>{{ factor.description }}</p>
        </div>
        
        <div v-if="factor.extraGuidelines && factor.extraGuidelines !== '<!-- Add extra guidelines here -->'" class="factor-guidelines">
          <strong>Additional Guidelines:</strong>
          <div v-html="factor.extraGuidelines"></div>
        </div>
        
        <div class="factor-labels" v-if="factor.labels && factor.labels.length > 0">
          <strong>Rating Labels:</strong>
          <table class="labels-table">
            <thead>
              <tr>
                <th>Rating</th>
                <th>Label</th>
                <th v-if="hasHoverText(factor)">Additional Context</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="label in factor.labels" :key="label.value">
                <td class="rating-value">{{ label.value }}</td>
                <td class="label-text">{{ label.text }}</td>
                <td v-if="hasHoverText(factor) && factor.hoverText && factor.hoverText[label.value]" class="hover-text">
                  {{ factor.hoverText[label.value] }}
                </td>
                <td v-else-if="hasHoverText(factor)"></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    
    <div v-if="template.footer.customContent && template.footer.customContent !== '<!-- Add custom footer content here -->'" class="help-footer" v-html="template.footer.customContent"></div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import ratingFactorsData from '../data/rating-factors.json';

const template = ref(ratingFactorsData);

function hasHoverText(factor: any): boolean {
  return factor.hoverText && Object.keys(factor.hoverText).length > 0;
}
</script>

<style scoped>
.rating-factors-help {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  line-height: 1.6;
  color: #333;
}

.help-header {
  margin-bottom: 40px;
  padding-bottom: 20px;
  border-bottom: 2px solid #e0e0e0;
}

.help-header h1 {
  margin: 0 0 10px 0;
  color: #2c3e50;
}

.rating-factors-list {
  display: flex;
  flex-direction: column;
  gap: 40px;
}

.rating-factor-section {
  background: #f9f9f9;
  padding: 25px;
  border-radius: 8px;
  border-left: 4px solid #3498db;
}

.factor-title {
  margin: 0 0 15px 0;
  color: #2c3e50;
  font-size: 1.4em;
}

.factor-number {
  color: #3498db;
  margin-right: 10px;
}

.factor-meta {
  display: flex;
  gap: 20px;
  margin-bottom: 15px;
  flex-wrap: wrap;
}

.meta-item {
  font-size: 0.9em;
  color: #666;
}

.meta-item code {
  background: #e8e8e8;
  padding: 2px 6px;
  border-radius: 3px;
  font-family: 'Courier New', monospace;
  font-size: 0.9em;
}

.factor-description,
.factor-guidelines {
  margin: 15px 0;
  padding: 15px;
  background: white;
  border-radius: 5px;
}

.factor-description strong,
.factor-guidelines strong {
  display: block;
  margin-bottom: 8px;
  color: #2c3e50;
}

.factor-labels {
  margin-top: 20px;
}

.factor-labels strong {
  display: block;
  margin-bottom: 10px;
  color: #2c3e50;
}

.labels-table {
  width: 100%;
  border-collapse: collapse;
  background: white;
  border-radius: 5px;
  overflow: hidden;
}

.labels-table thead {
  background: #3498db;
  color: white;
}

.labels-table th,
.labels-table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #e0e0e0;
}

.labels-table th {
  font-weight: 600;
}

.rating-value {
  font-weight: bold;
  color: #3498db;
  width: 80px;
}

.label-text {
  color: #333;
}

.hover-text {
  color: #666;
  font-style: italic;
  font-size: 0.9em;
}

.help-footer {
  margin-top: 40px;
  padding-top: 20px;
  border-top: 2px solid #e0e0e0;
}
</style>
